# Generated by Django 3.2.9 on 2021-11-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prince',
            new_name='price',
        ),
    ]
