# Generated by Django 3.2.9 on 2021-11-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_prince_recipe_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_miniutes',
            new_name='time_minutes',
        ),
    ]
