# Generated by Django 3.2.9 on 2021-11-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_time_miniutes_recipe_time_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingregiants',
            new_name='ingrediants',
        ),
    ]
