name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Testing Django Application
      run: docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"
